Typography Update
werkbot/framewerk pull request #16
Opened 2022-03-04 15:57 UTC by aletail

### Ticket Link
https://werkbotstudios.teamwork.com/#/tasks/27811857

### Summary
> Broke out the typography section into separate configurable files

### Testing Steps
- [ ] Test out basic elements, confirm the defaults function as expected
- [ ] Try to override some of the elements, confirm this functions as expected

2022-03-07 20:44 UTC, aletail commented
> Properties have been added here that are not present in framewerk\docs\en\form.md. Maybe add these to the documentation branch?

I will make a new task to update documentation, I think this will be on going as we tweak and iron things out.

2022-03-07 21:34 UTC, tiller1010 requested changes
I noticed that some of the form component properties here are unused in favor of the theme properties.

2022-03-07 21:34 UTC, tiller1010 commented on sass/components/form/components/_select.scss
> +      color: getThemeProperty(textColorDark, $component-form-select-properties);
This is set to the theme property `textColorDark`, not the select `color` property. Also, this component has a `textColor` property.

2022-03-07 21:34 UTC, tiller1010 commented on sass/components/form/components/_text.scss
> +      color: getThemeProperty(textColorDark, $component-form-text-properties);
Same thing here, this is a theme property.

2022-03-07 21:34 UTC, tiller1010 commented on sass/components/form/components/_text.scss
> +  fontFamily: getThemeProperty(fontText),
This is unused.

2022-03-07 21:34 UTC, tiller1010 commented on sass/components/form/components/_text.scss
> +      font-family: getThemeProperty(fontText, $component-form-text-properties);
This is the theme property

2022-03-07 21:34 UTC, tiller1010 commented on sass/components/form/components/_textarea.scss
> +      font-family: getThemeProperty(fontText, $component-form-textarea-properties);
Same issues here

2022-03-07 22:02 UTC, aletail commented
@tiller1010 I think I have these straighten out - we may need to re-visit this and update the naming conventions so its easier to keep track of haha

2022-03-08 17:35 UTC, aletail commented
> Unrelated, but could we remove the calc() calls added here? https://github.com/werkbot/framewerk/pull/17/files they do not work with the sass builds (they give invalid property values and cause the build to fail), and they are only warnings in the webpack build.

Sure, any idea why they were added? I will remove and test them as a part of this PR

2022-03-08 21:10 UTC, tiller1010 approved these changes
Spectacular!

2022-03-09 12:37 UTC, merged