Feature/space breakpoints
werkbot/framewerk pull request #63
Opened 2023-03-17 14:43 UTC by aletail

https://werkbotstudios.teamwork.com/app/tasks/31552876

### Summary
> Added the ability to specify the padding/spacing per responsive breakpoint

### Testing Steps
- [x] Test with Erie Injury (Any site really) - be sure to rebuild your sass with this in place
- [x] Try to override default spacing classes by adding `fw-space-tablet-double`, `fw-space-phone-half` etc...(In templates or even in the inspector)
- [ ] Confirm this works as expected
- [ ] Confirm the default desktop spacing works as it did before

### Issues/Concerns
- This should not break any previous sites, just adds extra functionality

### Git Flow
- **DO NOT** delete "release/\*" or "hotfix/\*" branches after merging a PR. These are used to publish the next release, and they are deleted automatically.
- "Squash and merge" is good on "feature/\*" into "develop"
- "Create a merge commit" is good on "release/\*" or "hotfix/\*" into "master"

2023-03-17 17:17 UTC, tiller1010 requested changes
This is looking really cool!

If `fw-space` has any modifier class (even "default") then the responsive style rule is not specific enough to be applied.
![image](https://user-images.githubusercontent.com/42498429/225972236-73c27295-3935-4f17-9940-ed856f021992.png)

2023-03-17 17:17 UTC, tiller1010 commented on sass/base/space/_space.scss
> +			.fw-space-#{$label}-#{$spacelabel}{
I think a good workaround to make this more specific is to include `.fw-space` in the selector:
```scss
.fw-space.fw-space-#{$label}-#{$spacelabel}{
```

2023-03-17 17:17 UTC, tiller1010 commented on sass/base/space/_space.scss
> +    default: getThemeProperty(layoutSpace),
The only issue with my suggestion is that someone might want to apply padding on mobile, but not on desktop. To force the inclusion of the `fw-space` class for `fw-space-phone-default` to works means that the space will appear on desktop as well as on mobile. To workaround this, a "none" modifier could be added:
```scss
$default-base-space-properties:(
  paddingclasses:(
    none: 0,
```
That way an element with the classes: "fw-space none fw-space-phone-default" works the way that you would expect.

2023-03-20 15:54 UTC, aletail commented
@tiller1010 Give this another look when you can

2023-03-20 18:09 UTC, tiller1010 requested changes
This is cool! But the positional padding classes do not work on desktop.
If I were to add a "doubleleft" class, "fw-space.fw-space-tablet-doubleleft" works as I would expect, but "fw-space doubleleft" does not.

Also, we could use a `$positions` list to reduce the amount of code here:
```scss
$positions: top, right, bottom, left;

// Default spacing - desktop
.fw-space,
.space{
  padding: getThemeProperty(layoutSpace);
  @each $label, $value in getThemeProperty("paddingclasses", $base-space-properties){
    &.#{$label}{
      padding: #{$value};
    }
  }

  @each $position in $positions {
    @each $label, $value in getThemeProperty(padding#{$position}classes, $base-space-properties) {
      &.#{$label}{
        padding-#{$position}: #{$value};
      }
    }
  }
}

// For each responsive breakpoint, create a space class
@each $label, $breakpoint in getThemeProperty(breakpointResponsive){
  @media only screen and (max-width: $breakpoint) {
    @each $spacelabel, $value in getThemeProperty("paddingclasses", $base-space-properties){
      .fw-space.fw-space-#{$label}-#{$spacelabel}{
        padding: #{$value};
      }
    }

    @each $position in $positions {
      @each $spacelabel, $value in getThemeProperty(padding#{$position}classes, $base-space-properties) {
        .fw-space.fw-space-#{$label}-#{$spacelabel}{
          padding-#{$position}: #{$value};
        }
      }
    }
  }
}
```

2023-03-21 16:36 UTC, aletail commented
> But the positional padding classes do not work on desktop. If I were to add a "doubleleft" class, "fw-space.fw-space-tablet-doubleleft" works as I would expect, but "fw-space doubleleft" does not.

I forgot to add the code for that section

> Also, we could use a $positions list to reduce the amount of code...

Nice, I like this - updated

2023-03-21 16:54 UTC, tiller1010 approved these changes
Awesome!

2023-03-21 18:15 UTC, merged